version: "3"

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    networks:
      - app-network

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8088:80"
    volumes:
      - .:/var/www
    networks:
      - app-network

  redis:
    image: redis:5.0.6-alpine
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
