apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: img-app-deployment
          ports:
            - containerPort: 80
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-pass
          envFrom:
            - configMapRef:
                name: app-conf
          volumeMounts:
            - mountPath: /var/www/.env
              subPath: .env
              name: app-conf
      volumes:
        - name: app-conf
          configMap:
            name: app-conf
            items:
              - key: env
                path: .env
